In [2]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')

In [4]:
# initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [5]:
Q.shape

(16, 4)

In [6]:
lr = .8
gamma = .95
n_episodes = 2000

In [7]:
rewards = []
for i in range(n_episodes):
    s = env.reset()  # reset environment and get first new observation
    total_reward = 0
    d = False
    j = 0
    while j < 99:
        j += 1
        # Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n) * (1. / (i + 1)))
        
        s1, r, d, _ = env.step(a)
        
        # update table
        Q[s, a] = Q[s, a] + lr * (r + gamma * np.max(Q[s1, :]) - Q[s, a])
        total_reward += r
        s = s1
        if d == True:
            break
            
    rewards.append(total_reward)

In [8]:
print('Score over time:', str(sum(rewards) / n_episodes))
print('Final Q-Table values:')
print(Q)

Score over time: 0.65
Final Q-Table values:
[[1.39762363e-01 1.49028982e-02 8.79905961e-03 1.10563487e-02]
 [2.22557591e-03 2.31520120e-05 1.07700785e-02 1.23715991e-01]
 [2.92540497e-01 9.03140431e-03 6.58335663e-03 7.18047574e-03]
 [1.08966464e-03 6.12594768e-03 0.00000000e+00 6.87281326e-03]
 [1.76996386e-01 2.09695531e-03 2.86969484e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.33248172e-01 2.02435740e-04 2.32914721e-04 8.47581268e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.92982416e-04 2.24383291e-03 5.25122410e-01]
 [1.13027144e-02 4.35658492e-01 0.00000000e+00 0.00000000e+00]
 [6.20526241e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.52683862e-01 0.00000000e+00]
 [0.00000000e+00 9.69549477e-01 0.00000000e+00 0.00000000e+00]
 [0.0000000